version: '3'
services:
  web:
    build: .
    volumes:
      - ./:/go/src/github.com/Scalingo/sclng-backend-test-v1
    ports:
      - "5000:5000"
    environment:
    - GITHUB_API_KEY=${GITHUB_API_KEY}
    command: reflex -r '\.go$$' -s -- sh -c 'go build -mod=vendor && ./sclng-backend-test-v1'
